# Generated by Django 3.0.13 on 2021-04-06 16:03

from django.db import migrations, models

import nbank_registry.tools


class Migration(migrations.Migration):
    dependencies = [
        ("nbank_registry", "0002_auto_20180511_1141"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archive",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="datatype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.SlugField(
                default=nbank_registry.tools.random_id, max_length=255, unique=True
            ),
        ),
    ]
