# Generated by Django 3.0.13 on 2021-04-06 16:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nbank_registry", "0003_auto_20210406_1203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
