# Generated by Django 3.0.13 on 2021-09-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nbank_registry", "0004_auto_20210406_1211"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatype",
            name="downloadable",
            field=models.BooleanField(default=False),
        ),
    ]
