# Generated by Django 5.1.4 on 2025-07-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nbank_registry", "0008_alter_datatype_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="accessibility",
            field=models.IntegerField(
                choices=[(0, "local"), (1, "remote"), (2, "offline")], default=0
            ),
        ),
    ]
