# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurobank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domain',
            new_name='Archive',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='domain',
            new_name='archive',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('resource', 'archive')]),
        ),
    ]
