# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurobank', '0002_auto_20170624_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='method',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='root',
        ),
        migrations.AddField(
            model_name='domain',
            name='remote',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='url',
            field=models.CharField(default='', help_text='Root path for resources. Include method and authority for remote resources', max_length=512),
            preserve_default=False,
        ),
    ]
