# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurobank', '0003_auto_20170624_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
