# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurobank', '0004_auto_20170624_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='uuid',
            new_name='name',
        ),
    ]
