# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurobank', '0005_auto_20170624_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(help_text='A descriptive name', max_length=32, unique=True),
        ),
    ]
