# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurobank', '0006_auto_20170624_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='sha1',
            field=models.CharField(blank=True, help_text='specify only for resources whose contents must not change (i.e., sources)', max_length=40, null=True),
        ),
    ]
