# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neurobank', '0007_resource_sha1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurobank.Domain'),
        ),
        migrations.AlterField(
            model_name='location',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurobank.Resource'),
        ),
    ]
