# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurobank', '0009_auto_20170626_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='remote',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='url',
        ),
        migrations.AddField(
            model_name='datatype',
            name='content_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='root',
            field=models.CharField(default='', help_text='Root path for resources.', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='scheme',
            field=models.CharField(default='neurobank', max_length=16),
            preserve_default=False,
        ),
    ]
