# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurobank', '0011_auto_20170626_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.SlugField(help_text='a descriptive name', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='root',
            field=models.CharField(help_text='root path for resources', max_length=512),
        ),
    ]
