# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neurobank', '0013_auto_20170627_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='registered',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
